apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frps

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: frps
  version: "0.64.0"

images:
  - name: ccr.ccs.tencentyun.com/ray321/frps
    newTag: "0.64.0"
