apiVersion: v1
kind: Service
metadata:
  name: frps-service
spec:
  type: ClusterIP
  selector:
    app: frps
  ports:
    - name: frps-port
      protocol: TCP
      port: 7000
      targetPort: 7000
    - name: dashboard-port
      protocol: TCP
      port: 7500
      targetPort: 7500
    - name: pve-port
      protocol: TCP
      port: 6001
      targetPort: 6001
    - name: ikuai-port
      protocol: TCP
      port: 6002
      targetPort: 6002
    - name: istoreos-port
      protocol: TCP
      port: 6003
      targetPort: 6003
