apiVersion: v1
kind: Service
metadata:
  name: frps-service
spec:
  type: NodePort
  selector:
    app: frps
  ports:
    - name: frps-port
      protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30000
    - name: dashboard-port
      protocol: TCP
      port: 7500
      targetPort: 7500
      nodePort: 30001
